/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dingran_curltest_test_JniTest */

#ifndef _Included_dingran_curltest_test_JniTest
#define _Included_dingran_curltest_test_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dingran_curltest_test_JniTest
 * Method:    curlInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xwpeng_tkotlin_CurlTest_curlTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
